# Generated by Django 5.0.7 on 2024-08-27 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='phone_number',
            field=models.CharField(help_text='Enter number to receive calls from users. Format: +<country_code> <9_digits>', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: +<country_code> <9_digits>.', regex='^\\+\\d{1,3} \\d{9}$')]),
        ),
    ]
